/**
 * Lucide-to-AntD icon mapping reference.
 * Used during Phase 3 migration — can be deleted after all pages are migrated.
 */

export const LUCIDE_TO_ANTD: Record<string, string> = {
  AlertCircle: "ExclamationCircleOutlined",
  AlertTriangle: "WarningOutlined",
  AlignCenter: "AlignCenterOutlined",
  AlignLeft: "AlignLeftOutlined",
  AlignRight: "AlignRightOutlined",
  ArrowLeft: "ArrowLeftOutlined",
  ArrowRight: "ArrowRightOutlined",
  ArrowUp: "ArrowUpOutlined",
  ArrowUpDown: "SwapOutlined",
  Ban: "StopOutlined",
  Bold: "BoldOutlined",
  BookOpen: "ReadOutlined",
  Building2: "BankOutlined",
  Calendar: "CalendarOutlined",
  CalendarDays: "CalendarOutlined",
  CalendarPlus: "CalendarOutlined",
  Check: "CheckOutlined",
  CheckCircle: "CheckCircleOutlined",
  CheckCircle2: "CheckCircleFilled",
  ChevronDown: "DownOutlined",
  ChevronLeft: "LeftOutlined",
  ChevronRight: "RightOutlined",
  ClipboardList: "SnippetsOutlined",
  Clock: "ClockCircleOutlined",
  Columns2: "ColumnWidthOutlined",
  Copy: "CopyOutlined",
  Database: "DatabaseOutlined",
  Edit3: "EditOutlined",
  ExternalLink: "LinkOutlined",
  Eye: "EyeOutlined",
  EyeOff: "EyeInvisibleOutlined",
  FileSpreadsheet: "FileExcelOutlined",
  FileText: "FileTextOutlined",
  Filter: "FilterOutlined",
  FolderPlus: "FolderAddOutlined",
  Grid3X3: "TableOutlined",
  GripVertical: "HolderOutlined",
  Hash: "NumberOutlined",
  History: "HistoryOutlined",
  Image: "PictureOutlined",
  Info: "InfoCircleOutlined",
  Italic: "ItalicOutlined",
  LayoutGrid: "AppstoreOutlined",
  Lightbulb: "BulbOutlined",
  Link2: "LinkOutlined",
  List: "UnorderedListOutlined",
  ListOrdered: "OrderedListOutlined",
  Lock: "LockOutlined",
  Mail: "MailOutlined",
  MapPin: "EnvironmentOutlined",
  Menu: "MenuOutlined",
  MessageCircle: "MessageOutlined",
  Minus: "MinusOutlined",
  Monitor: "DesktopOutlined",
  MoreHorizontal: "MoreOutlined",
  Paperclip: "PaperClipOutlined",
  Pencil: "EditOutlined",
  Phone: "PhoneOutlined",
  Plus: "PlusOutlined",
  Printer: "PrinterOutlined",
  Repeat: "SyncOutlined",
  RotateCcw: "UndoOutlined",
  Search: "SearchOutlined",
  Send: "SendOutlined",
  Settings: "SettingOutlined",
  Share2: "ShareAltOutlined",
  Sparkles: "ThunderboltOutlined",
  Trash2: "DeleteOutlined",
  ToggleLeft: "SwitcherOutlined",
  Type: "FontSizeOutlined",
  Underline: "UnderlineOutlined",
  Upload: "UploadOutlined",
  User: "UserOutlined",
  UserPlus: "UserAddOutlined",
  Users: "TeamOutlined",
  Video: "VideoCameraOutlined",
  X: "CloseOutlined",
};

export const LUCIDE_SIZE_MAP: Record<string, number> = {
  "h-3 w-3": 12,
  "h-3.5 w-3.5": 14,
  "h-4 w-4": 16,
  "h-5 w-5": 20,
  "h-6 w-6": 24,
  "h-8 w-8": 32,
  "h-10 w-10": 40,
  "h-12 w-12": 48,
};
